INSERT into categories (cat_code, cat_name) VALUES ('AP','Appetizer');
INSERT into categories (cat_code, cat_name) VALUES ('SP','Soup');
INSERT into categories (cat_code, cat_name) VALUES ('SL','Salad');
INSERT into categories (cat_code, cat_name) VALUES ('VG','Vegetable');
INSERT into categories (cat_code, cat_name) VALUES ('BG','Bean&Grain');
INSERT into categories (cat_code, cat_name) VALUES ('PS','Pasta');
INSERT into categories (cat_code, cat_name) VALUES ('HL','Holiday');
INSERT into categories (cat_code, cat_name) VALUES ('PR','Party');
INSERT into categories (cat_code, cat_name) VALUES ('MT','Meat');
INSERT into categories (cat_code, cat_name) VALUES ('VE','Vegan');
INSERT into categories (cat_code, cat_name) VALUES ('FS','Fish');
INSERT into categories (cat_code, cat_name) VALUES ('DS','Dessert');
INSERT into categories (cat_code, cat_name) VALUES ('BK','Pizza & Bread');