INSERT into ingredients (name) VALUES('baby spinach leaves');
INSERT into ingredients (name) VALUES('eggs');
INSERT into ingredients (name) VALUES('salt');
INSERT into ingredients (name) VALUES('nutmeg');
INSERT into ingredients (name) VALUES('pepper');
INSERT into ingredients (name) VALUES('flour');
INSERT into ingredients (name) VALUES('butter');
INSERT into ingredients (name) VALUES('bacon');
INSERT into ingredients (name) VALUES('sage');
INSERT into ingredients (name) VALUES('Parmesan');
INSERT into ingredients (name) VALUES('vegetable oil');
INSERT into ingredients (name) VALUES('dried red chiles');
INSERT into ingredients (name) VALUES('snow peas');
INSERT into ingredients (name) VALUES('scallion');
INSERT into ingredients (name) VALUES('garlic');
INSERT into ingredients (name) VALUES('ginger');
INSERT into ingredients (name) VALUES('toasted sesame oil');
INSERT into ingredients (name) VALUES('roasted peanuts');
INSERT into ingredients (name) VALUES('cilantro');
INSERT into ingredients (name) VALUES('lamb shanks');
INSERT into ingredients (name) VALUES('pepper');
INSERT into ingredients (name) VALUES('cumin');
INSERT into ingredients (name) VALUES('paprika');
INSERT into ingredients (name) VALUES('onion');
INSERT into ingredients (name) VALUES('saffron');
INSERT into ingredients (name) VALUES('cayenn pepper');
INSERT into ingredients (name) VALUES('tomato paste');
INSERT into ingredients (name) VALUES('cinnamon stick');
INSERT into ingredients (name) VALUES('dates');
INSERT into ingredients (name) VALUES('golden raisins');
INSERT into ingredients (name) VALUES('pomegranate seeds');