INSERT into ingredients (name) VALUES('baby spinach leaves');
INSERT into ingredients (name) VALUES('eggs');
INSERT into ingredients (name) VALUES('salt');
INSERT into ingredients (name) VALUES('nutmeg');
INSERT into ingredients (name) VALUES('pepper');
INSERT into ingredients (name) VALUES('flour');
INSERT into ingredients (name) VALUES('butter');
INSERT into ingredients (name) VALUES('bacon');
INSERT into ingredients (name) VALUES('sage');
INSERT into ingredients (name) VALUES('Parmesan');