insert into x_recipe_ingredient (recipe_fk,ingredient_name,ingredient_info,quantity,measure) VALUES (1,'baby spinach leaves',' or equivalent quantity of larger leaves','5','ounces');
insert into x_recipe_ingredient (recipe_fk,ingredient_name,ingredient_info,quantity,measure) VALUES (1,'egg','','4','');
insert into x_recipe_ingredient (recipe_fk,ingredient_name,ingredient_info,quantity,measure) VALUES (1,'egg','yolk','4','');
insert into x_recipe_ingredient (recipe_fk,ingredient_name,ingredient_info,quantity,measure) VALUES (1,'salt','','','');
insert into x_recipe_ingredient (recipe_fk,ingredient_name,ingredient_info,quantity,measure) VALUES (1,'nutmeg','grated','1/4','teaspoon');
insert into x_recipe_ingredient (recipe_fk,ingredient_name,ingredient_info,quantity,measure) VALUES (1,'pepper','black','1','teaspoon');
insert into x_recipe_ingredient (recipe_fk,ingredient_name,ingredient_info,quantity,measure) VALUES (1,'flour','all-purpose','3 ¼','cup');
insert into x_recipe_ingredient (recipe_fk,ingredient_name,ingredient_info,quantity,measure) VALUES (1,'butter','','4','tablespoons');
insert into x_recipe_ingredient (recipe_fk,ingredient_name,ingredient_info,quantity,measure) VALUES (1,'bacon','or pancetta, cut crosswise into thin lardons','4','ounces');
insert into x_recipe_ingredient (recipe_fk,ingredient_name,ingredient_info,quantity,measure) VALUES (1,'sage','fresh','12','leaves');
insert into x_recipe_ingredient (recipe_fk,ingredient_name,ingredient_info,quantity,measure) VALUES (1,'Parmesan','grated','','');
insert into x_recipe_ingredient (recipe_fk,ingredient_name,ingredient_info,quantity,measure) VALUES (2,'vegetable oil','','2','tablespoons');
insert into x_recipe_ingredient (recipe_fk,ingredient_name,ingredient_info,quantity,measure) VALUES (2,'dried red chiles','small','6 to 8','');
insert into x_recipe_ingredient (recipe_fk,ingredient_name,ingredient_info,quantity,measure) VALUES (2,'snow peas',', trimmed','1','pound');
insert into x_recipe_ingredient (recipe_fk,ingredient_name,ingredient_info,quantity,measure) VALUES (2,'scallion',', trimmed, chopped in 1-inch lengths','1','bunch');
insert into x_recipe_ingredient (recipe_fk,ingredient_name,ingredient_info,quantity,measure) VALUES (2,'garlic',', minced','4','cloves');
insert into x_recipe_ingredient (recipe_fk,ingredient_name,ingredient_info,quantity,measure) VALUES (2,'ginger','grated','½','teaspoon');
insert into x_recipe_ingredient (recipe_fk,ingredient_name,ingredient_info,quantity,measure) VALUES (2,'toasted sesame oil','','½','teaspoon');
insert into x_recipe_ingredient (recipe_fk,ingredient_name,ingredient_info,quantity,measure) VALUES (2,'roasted peanuts','crushed','3','tablespoons');
insert into x_recipe_ingredient (recipe_fk,ingredient_name,ingredient_info,quantity,measure) VALUES (2,'cilantro','','','');
insert into x_recipe_ingredient (recipe_fk,ingredient_name,ingredient_info,quantity,measure) VALUES (3,'lamb shanks','','3','');
insert into x_recipe_ingredient (recipe_fk,ingredient_name,ingredient_info,quantity,measure) VALUES (3,'salt and pepper','','','');
insert into x_recipe_ingredient (recipe_fk,ingredient_name,ingredient_info,quantity,measure) VALUES (3,'garlic',' cloves, minced','6','');
insert into x_recipe_ingredient (recipe_fk,ingredient_name,ingredient_info,quantity,measure) VALUES (3,'paprika','','1','tablespoon');
insert into x_recipe_ingredient (recipe_fk,ingredient_name,ingredient_info,quantity,measure) VALUES (3,'cumin','ground','','');
insert into x_recipe_ingredient (recipe_fk,ingredient_name,ingredient_info,quantity,measure) VALUES (3,'butter','','2','tablespoons');
insert into x_recipe_ingredient (recipe_fk,ingredient_name,ingredient_info,quantity,measure) VALUES (3,'onion',', sliced, about 2 cups','1','');
insert into x_recipe_ingredient (recipe_fk,ingredient_name,ingredient_info,quantity,measure) VALUES (3,'saffron','','1','small pinch');
insert into x_recipe_ingredient (recipe_fk,ingredient_name,ingredient_info,quantity,measure) VALUES (3,'cayenne pepper','','½','teaspoon');
insert into x_recipe_ingredient (recipe_fk,ingredient_name,ingredient_info,quantity,measure) VALUES (3,'tomato paste','','1','tablespoon');
insert into x_recipe_ingredient (recipe_fk,ingredient_name,ingredient_info,quantity,measure) VALUES (3,'cinnamon stick','','1','');
insert into x_recipe_ingredient (recipe_fk,ingredient_name,ingredient_info,quantity,measure) VALUES (3,'dried ginger','','2','tablespoons');
insert into x_recipe_ingredient (recipe_fk,ingredient_name,ingredient_info,quantity,measure) VALUES (3,'dates',', chopped','½','cup');
insert into x_recipe_ingredient (recipe_fk,ingredient_name,ingredient_info,quantity,measure) VALUES (3,'golden raisins',', soaked in hot water to soften for 30 minutes and drained','½','cup');
insert into x_recipe_ingredient (recipe_fk,ingredient_name,ingredient_info,quantity,measure) VALUES (3,'pomegranate seeds','','½','cup');
insert into x_recipe_ingredient (recipe_fk,ingredient_name,ingredient_info,quantity,measure) VALUES (3,' Cilantro sprigs, for garnish','','','');