INSERT into recipes (title, description, image_url, cat_code, cuisine, calories, rate, servings, cook_time, skill_level, source) VALUES ('Spinach Spaetzle With Bacon and Sage','Spaetzle, the delicious little German dumplings (sometimes called batter noodles).These are green spaetzle, made with spinach purée, sizzled with bacon and sage leaves. (Instead of spinach, you could add chopped herbs, but plain spaetzle are divine, too.) Spaetzle take only moments to cook and can be prepared in advance, then sautéed in butter to serve.','PS_1.jpg','PS','German','','Delicious',6,'1 hour','M','NYT');
INSERT into recipes (title, description, image_url, cat_code, cuisine, calories, rate, servings, cook_time, skill_level, source) VALUES ('Spicy Wok-Charred Snow Peas','High-heat stir-fries are ideal for peas — either snow peas or the sugar snap variety. Assertive seasoning and the slight charring from the wok complement the peas’ sweetness wonderfully. The method works well for other spring vegetables, too, like asparagus or baby bok choy clusters. Use a wide cast -iron pan if you don’t have a wok. Take care to avoid overcooking; the peas should be a vibrant green color and firm to the bite.','VG_2.jpg','VG','American','','Delicious',6,'15 minutes','E','NYT');
INSERT into recipes (title, description, image_url, cat_code, cuisine, calories, rate, servings, cook_time, skill_level, source) VALUES ('Lamb Shank Tagine With Dates','For the best stews, use lamb shanks simmered slowly on the bone. Here, Moroccan seasonings mingle for a bright balance of flavors: sweetness comes from dates and onions, and heat and spice from ginger and cumin. This tagine is traditionally accompanied only by warm whole wheat pita or Arab flatbread. But, if you wish, serve with buttered couscous or even mashed potatoes. Roasted parsnips or wilted mustard greens would harmonize well, too.','','MT','Moroccan','','Delicious',6,'3 1/2 hours ','D','NYT');

INSERT INTO recipes (title, description, image_url, cat_code, cuisine, calories, rate, servings, cook_time, skill_level, source) VALUES ('Olive Oil Mashed Potatoes','These mashed potatoes are extremely easy to make, and have the added benefit of being vegan. A hefty dose of garlic lends a bite to the creaminess. Make sure to use good olive oil.','VG_4.jpg','VG','Italian',NULL,NULL,NULL,6,'20 minutes','E');
INSERT INTO recipes (title, description, image_url, cat_code, cuisine, calories, rate, servings, cook_time, skill_level, source) VALUES ('Roasted Veggie Tarts','You can use a mini-muffin tray to form the shells of her crowd-pleasing butternut squash and zucchini mini-tarts. The vegetable filling is made quick and easy by using a wok to cook the vegetables.','VG_3.jpg','AP','International',NULL,NULL,NULL,4,'45 minutes','M');
INSERT INTO recipes (title, description, image_url, cat_code, cuisine, calories, rate, servings, cook_time, skill_level, source) VALUES ('Squash and Celeriac Quinoa Stuffing','Vegans and non-vegans will enjoy this twist on a traditional stuffing, where quinoa replaces the bread and butternut squash, celeriac and hazelnuts add the flavors of fall.','VG.jpg','VE','International',NULL,NULL,NULL,6,'45 minutes','E');
INSERT INTO recipes (title, description, image_url, cat_code, cuisine, calories, rate, servings, cook_time, skill_level, source) VALUES ('Pear-Pomegranate Pie ','In this welcome departure from the traditional apple pie, a combination of Anjou and Bosc pears are caramelized in a mixture of pomegranate molasses and butter, then combined with a smaller portion of fresh, uncooked pears. The whole glorious mess is then dumped into an all-butter crust and baked until tender. The happy result is a pie that''s soft and sweet, tangy and toothsome, and oh so good.','DS_2.jpg','DS','International',NULL,NULL,NULL,8,'1 hour 30 minutes','M');
INSERT INTO recipes (title, description, image_url, cat_code, cuisine, calories, rate, servings, cook_time, skill_level, source) VALUES ('Broccoli Rabe Lasagna','Broccoli rabe (sometimes spelled raab, or known as rapini greens) is one of the most delicious members of the mustard green family. The leaves, tender stems and broccoli-like buds have a distinctive pleasant bitterness when cooked. For this vegetarian lasagna, some of the cooked greens are puréed to make a garlicky pesto and the rest is coarsely chopped and added to the layers.','PT_2.jpg','PS','Italian',NULL,NULL,NULL,6,'1 hour 30 minutes','D');
INSERT INTO recipes (title, description, image_url, cat_code, cuisine, calories, rate, servings, cook_time, skill_level, source) VALUES ('Spinach Spaetzle With Bacon and Sage','Spaetzle, the delicious little German dumplings (sometimes called batter noodles).These are green spaetzle, made with spinach purée, sizzled with bacon and sage leaves. (Instead of spinach, you could add chopped herbs, but plain spaetzle are divine, too.) Spaetzle take only moments to cook and can be prepared in advance, then sautéed in butter to serve.','PS_1.jpg','PS','German','','NYT','Delicious',6,'1 hour','M');
INSERT INTO recipes (title, description, image_url, cat_code, cuisine, calories, rate, servings, cook_time, skill_level, source) VALUES ('Spicy Wok-Charred Snow Peas','High-heat stir-fries are ideal for peas — either snow peas or the sugar snap variety. Assertive seasoning and the slight charring from the wok complement the peas’ sweetness wonderfully. The method works well for other spring vegetables, too, like asparagus or baby bok choy clusters. Use a wide cast -iron pan if you don’t have a wok. Take care to avoid overcooking; the peas should be a vibrant green color and firm to the bite.','VG_2.jpg','VG','American','','NYT','Delicious',6,'15 minutes','E');
INSERT INTO recipes (title, description, image_url, cat_code, cuisine, calories, rate, servings, cook_time, skill_level, source) VALUES ('Lamb Shank Tagine With Dates','For the best stews, use lamb shanks simmered slowly on the bone. Here, Moroccan seasonings mingle for a bright balance of flavors: sweetness comes from dates and onions, and heat and spice from ginger and cumin. This tagine is traditionally accompanied only by warm whole wheat pita or Arab flatbread. But, if you wish, serve with buttered couscous or even mashed potatoes. Roasted parsnips or wilted mustard greens would harmonize well, too.','MT_3.jpg','MT','Moroccan','','NYT','Delicious',6,'3 1/2 hours ','D');
